module(load="imtcp")
module(load="imudp")
module(load="imklog" permitnonkernelfacility="on")
module(load="omhttp")

input(type="imtcp" port="514" ruleset="remote")
input(type="imudp" port="514" ruleset="remote")

$template RemoteLogs,"/var/log/remote/%FROMHOST%/%$YEAR%-%$MONTH%-%$DAY%.log"

$template LaravelJson,"{\"message\":\"%msg%\",\"hostname\":\"%hostname%\",\"facility\":\"%syslogfacility-text%\",\"priority\":\"%syslogseverity-text%\",\"timestamp\":\"%timereported:::date-rfc3339%\",\"type\":\"system\"}\n"

ruleset(name="remote"){
    action(type="omfile" dynaFile="RemoteLogs")
    action(type="omstdout")
    action(type="omhttp"
        server="nginx"
        serverport="80"
        restpath="api/logs"
        template="LaravelJson"
        action.resumeRetryCount="3"
    )
}
